-- MySQL Script generated by MySQL Workbench
-- Wed May 10 21:10:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appleSpace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appleSpace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appleSpace` DEFAULT CHARACTER SET utf8 ;
USE `appleSpace` ;

-- -----------------------------------------------------
-- Table `appleSpace`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appleSpace`.`user` ;

CREATE TABLE IF NOT EXISTS `appleSpace`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `pwd` VARCHAR(100) NULL,
  `admin` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appleSpace`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appleSpace`.`order` ;

CREATE TABLE IF NOT EXISTS `appleSpace`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `total` DECIMAL(10,2) NULL,
  `delivery` DATE NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `appleSpace`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appleSpace`.`product_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appleSpace`.`product_type` ;

CREATE TABLE IF NOT EXISTS `appleSpace`.`product_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appleSpace`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appleSpace`.`product` ;

CREATE TABLE IF NOT EXISTS `appleSpace`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `price` DECIMAL(10,2) NULL,
  `discount` INT NULL,
  `description` VARCHAR(1000) NULL,
  `image` VARCHAR(100) NULL,
  `id_product_type` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_type_idx` (`id_product_type` ASC) VISIBLE,
  CONSTRAINT `fk_product_type`
    FOREIGN KEY (`id_product_type`)
    REFERENCES `appleSpace`.`product_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appleSpace`.`order_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appleSpace`.`order_item` ;

CREATE TABLE IF NOT EXISTS `appleSpace`.`order_item` (
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id_order`, `id_product`),
  INDEX `fk_product` (`id_product` ASC) VISIBLE,
  INDEX `fk_order` (`id_order` ASC) INVISIBLE,
  CONSTRAINT `fk_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `appleSpace`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `appleSpace`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
